In [21]:
import numpy as np
import keras
from keras.layers import Input, Flatten
from keras.models import Model
inputs = Input(shape=(3,2,4))

# Define a model consisting only of the Flatten operation
prediction = Flatten()(inputs)
model = Model(inputs=inputs, outputs=prediction)

X = np.arange(0,24).reshape(1,3,2,4)
print(X)

[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]]]]


In [22]:
model.predict(X)

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.]], dtype=float32)

In [23]:
keras.backend.set_image_data_format('channels_last')
# Define a model consisting only of the Flatten operation
inputs = Input(shape=(3,2,4))
prediction = Flatten()(inputs)
model = Model(inputs=inputs, outputs=prediction)
model.predict(X)

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.]], dtype=float32)

In [24]:
input_np = np.random.uniform(0, 1, (1, 20, 50, 50))

In [31]:
test = input_np.transpose(0,2,3,1)
test2 = test.transpose(0,3,1,2)

In [32]:
input_np.shape

(1, 20, 50, 50)

In [33]:
test.shape

(1, 50, 50, 20)

In [34]:
test2.shape

(1, 20, 50, 50)

In [35]:
test2 == input_np

array([[[[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ..., 
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ..., 
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ..., 
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,